### ISSUE TITLE
Lexmark X5150

### ISSUE THREAD

**Issue by quirinux-so** [nphilipp/xsane#2]
Hi. Is there a way to make the Lexmark X5150 scanner work? Out of the box XSANE does not recognize it.
sane-find-scanner
found USB scanner (vendor=0x043d [Lexmark], product=0x0065 [Lexmark X5100 Series]) at libusb:002:015

**Comment by nphilipp** [comment]
Hi, sorry for taking that long to respond, but I don't pay much attention to this repository, it’s pretty much just an archive of historical versions of xsane, no development happens here. The underlying SANE library actually provides the functionality, scanner models supported by it should be usable from within XSane. Howevery, this model doesn't seem to be supported: http://sane-project.org/sane-mfgs.html#Z-LEXMARK
